name: Build Package
on: [push]

jobs:
  build-ubuntu:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install conan
        run: |
          pip3 install wheel conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - uses: actions/checkout@v2
      - name: install
        run: conan install .
      - name: source
        run: conan source .
      - name: build
        run: conan build .
      - name: package
        run: conan package .
  build-windows:
    name: Package
    runs-on: windows-latest
    steps:
      - name: Install conan
        run: |
          pip install wheel conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - uses: actions/checkout@v2
      - name: install
        run: conan install .
      - name: source
        run: conan source .
      - name: build
        run: conan build .
      - name: package
        run: conan package .
